# Generated by Django 3.2.4 on 2021-08-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand_Logo_row1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='brand_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Logo_row2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='brand_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Brand_Logo_row3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('logo', models.ImageField(upload_to='brand_logo')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='simages')),
                ('category_wraper', models.CharField(blank=True, choices=[('Upper_Category', 'Upper_Category'), ('Books & Study', 'Books & Study'), ('Girls & Kids', 'Girls & Kids'), ('Cooking Essential', 'Cooking Essential'), ('Home Essential', 'Home Essential'), ('Fashion', 'Fashion'), ('Electronic', 'Electronic'), ('Handmade', 'Handmade'), ('Other', 'Other')], max_length=30, null=True)),
                ('cat_ref', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Colum1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Colum2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Colum3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Footer_Colum4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Mobile_Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('mobile_category_image', models.ImageField(upload_to='Mcataegory_image')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True)),
                ('slider_image', models.ImageField(upload_to='slider_image')),
                ('device', models.CharField(choices=[('Mobile', 'Mobile'), ('Desktop', 'Desktop')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('product_image', models.ImageField(upload_to='product_image')),
                ('selling_prize', models.FloatField()),
                ('discounted_prize', models.FloatField()),
                ('description', models.TextField()),
                ('brand', models.CharField(blank=True, max_length=100, null=True)),
                ('display_wraper', models.CharField(blank=True, choices=[('Shop With Deal', 'Shop With Deal'), ('Beauty Product', 'Beauty Product'), ('Mans Fashion', 'Mans Fashion')], max_length=30, null=True)),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('sell_amount', models.IntegerField(blank=True, null=True)),
                ('product_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
    ]
