# Generated by Django 3.2.4 on 2021-09-03 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210902_1937'),
    ]

    operations = [
        migrations.CreateModel(
            name='WraperCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('category_image', models.ImageField(upload_to='simages')),
                ('cat_ref', models.CharField(blank=True, max_length=20, null=True)),
                ('category_wraper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wrapercategory')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='display_wraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wrapercategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category'),
        ),
    ]
