# Generated by Django 3.2.4 on 2021-09-03 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210903_1214'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='display_wraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.displaywraper'),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_wraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.wrapercategory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='display_wraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.displaywraper'),
        ),
    ]
