# Generated by Django 3.2.4 on 2021-09-03 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210903_1521'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WraperCategory',
            new_name='CategoryWraper',
        ),
    ]
