# Generated by Django 3.2.4 on 2021-09-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_rename_wrapercategory_categorywraper'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorywraper',
            name='category_image',
            field=models.ImageField(blank=True, null=True, upload_to='category_wraper_image'),
        ),
    ]
