# Generated by Django 3.2.4 on 2021-09-03 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_categorywraper_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='categorywraper',
            name='display_wraper',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.displaywraper'),
        ),
    ]
