# Generated by Django 3.2.4 on 2021-09-03 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_categorywraper_display_wraper'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='cat_ref',
        ),
    ]
