# Generated by Django 3.2.4 on 2021-09-21 02:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_cart'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kg_Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('amount', models.IntegerField(blank=True, choices=[(1, '1kg'), (2, '2kg'), (3, '3kg')], default=1, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
