# Generated by Django 3.2.7 on 2021-09-29 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20210921_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='unit',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('ClothSize', 'ClothSize'), ('ClothPicesSize', 'ClothPicesSize'), ('ShoeSize', 'ShoeSize')], max_length=30, null=True),
        ),
    ]
