# Generated by Django 3.2.7 on 2021-09-29 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_cart_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalaryTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TestinImg', models.ImageField(upload_to='')),
            ],
        ),
    ]
