# Generated by Django 3.2.7 on 2021-09-29 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_galarytp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galarytp',
            old_name='TestinImg',
            new_name='Img',
        ),
    ]
