# Generated by Django 3.2.7 on 2021-09-30 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_testinimg_galarytp_img'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GalaryTP',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('ClothSize', 'ClothSize'), ('ClothPicesSize', 'ClothPicesSize'), ('ShoeSize', 'ShoeSize'), ('Packet', 'Packet')], max_length=30, null=True),
        ),
    ]
