# Generated by Django 3.2.7 on 2021-10-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210930_1224'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total_cost',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Liter', 'Liter'), ('KgPacket', 'KgPacket'), ('LiterPacket', 'LiterPacket'), ('ClothSize', 'ClothSize'), ('ClothPicesSize', 'ClothPicesSize'), ('ShoeSize', 'ShoeSize'), ('Packet', 'Packet')], max_length=30, null=True),
        ),
    ]
