# Generated by Django 3.2.7 on 2021-10-05 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_cart_unit_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total_cost',
        ),
    ]
