# Generated by Django 3.2.7 on 2021-10-10 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_customerprofile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
