# Generated by Django 3.2.7 on 2021-10-11 05:48

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20211011_1128'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator(message="phone_number must be entered in the format: ' +99999999'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')])),
                ('address', models.CharField(max_length=100)),
                ('districts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.districts')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.divisions')),
                ('unions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unions')),
                ('upazilas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.upazilas')),
            ],
        ),
    ]
