# Generated by Django 3.2.7 on 2021-10-11 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_address'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Address',
            new_name='CustomerAddress',
        ),
    ]
