# Generated by Django 3.2.7 on 2021-10-16 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_rename_address_customeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='division',
            new_name='divisions',
        ),
    ]
