# Generated by Django 3.2.7 on 2021-10-17 14:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_customeraddress_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='phone_number',
            field=models.CharField(max_length=16, validators=[django.core.validators.RegexValidator(message="phone_number must be entered in the format: ' +99999999'. Up to 15 digits allowed", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
