# Generated by Django 3.2.7 on 2021-10-18 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_customeraddress_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='isDefault',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
