# Generated by Django 3.2.7 on 2021-11-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_alter_customeraddress_isdefault'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unitValue',
            field=models.IntegerField(null=True),
        ),
    ]
