# Generated by Django 3.2.7 on 2021-11-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_product_unitvalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('SolidGroup', 'Kg'), ('LiquiedGroup', 'Liter'), ('KgPacket', 'KgPacket'), ('LiterPacket', 'LiterPacket'), ('ClothSize', 'ClothSize'), ('ClothPicesSize', 'ClothPicesSize'), ('ShoeSize', 'ShoeSize'), ('Packet', 'Packet')], max_length=30, null=True),
        ),
    ]
