# Generated by Django 3.2.7 on 2021-11-02 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_rename_unit_product_unitgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gram', 'Gram'), ('Pound', 'Pound'), ('Liter', 'Liter'), ('MiliLiter', 'MiliLiter')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitGroup',
            field=models.CharField(choices=[('Kg', 'Kg'), ('Gram', 'Gram'), ('Pound', 'Pound'), ('Liter', 'Liter'), ('MiliLiter', 'MiliLiter')], max_length=30, null=True),
        ),
    ]
