# Generated by Django 3.2.7 on 2021-11-02 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_auto_20211102_0917'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='MaximumUnitValue',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='MinimumUnitValue',
            field=models.IntegerField(null=True),
        ),
    ]
