# Generated by Django 3.2.7 on 2021-11-07 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(null=True),
        ),
    ]
