# Generated by Django 3.2.7 on 2021-11-13 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20211109_1137'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unitGroup',
        ),
        migrations.AddField(
            model_name='product',
            name='ProductGroup',
            field=models.CharField(blank=True, choices=[('SolidWeight', 'SolidWeight'), ('LiquidWeight', 'LiquidWeight'), ('KgPacket', 'KgPacket'), ('LiterPacket', 'LiterPacket'), ('Cloth', 'Cloth'), ('ClothPices', 'ClothPices'), ('Shoe', 'Shoe'), ('Packet', 'Packet')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('On the way', 'On the way'), ('Delivered', 'Delivered'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=50),
        ),
    ]
