# Generated by Django 3.2.7 on 2021-11-16 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20211113_0859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='MaximumUnitValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='MinimumUnitValue',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='ProductStock',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='unitValue_On_Increase_or_Decrease',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
