# Generated by Django 3.2.7 on 2021-11-20 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_alter_ptattribute_attributename'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeName', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeValue', models.FloatField()),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attribute')),
            ],
        ),
        migrations.RemoveField(
            model_name='ptattributevalue',
            name='ptAttribute',
        ),
        migrations.DeleteModel(
            name='PTAttribute',
        ),
        migrations.DeleteModel(
            name='PTAttributeValue',
        ),
    ]
