# Generated by Django 3.2.7 on 2021-11-20 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20211120_2013'),
    ]

    operations = [
        migrations.CreateModel(
            name='PTAttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attributeValue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attributevalue')),
                ('productType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.producttype')),
            ],
        ),
    ]
