# Generated by Django 3.2.7 on 2021-11-23 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_order_shippingcost'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_summuried',
            field=models.BooleanField(default=False),
        ),
    ]
