# Generated by Django 3.2.7 on 2021-11-23 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_order_is_summuried'),
    ]

    operations = [
        migrations.CreateModel(
            name='orderSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderItems', models.ManyToManyField(to='core.Order')),
            ],
        ),
    ]
