# Generated by Django 3.2.7 on 2021-11-23 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_ordersummary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordersummary',
            old_name='orderItems',
            new_name='orderItem',
        ),
    ]
