# Generated by Django 3.2.7 on 2021-11-24 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_rename_orderitems_ordersummary_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
