# Generated by Django 3.2.7 on 2021-11-24 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_ordersummary_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orderSummary',
        ),
    ]
