# Generated by Django 3.2.7 on 2021-11-24 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_ordersummary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='subTotal',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
