# Generated by Django 3.2.7 on 2021-11-24 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_auto_20211124_1908'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='coupon_or_discount',
            field=models.FloatField(default=0),
        ),
    ]
