# Generated by Django 3.2.7 on 2021-12-24 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_product_producttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattributevalue',
            name='productStock',
            field=models.FloatField(null=True),
        ),
    ]
