# Generated by Django 3.2.7 on 2021-12-25 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_rename_attributevaluename_attributevalue_attributevalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductGroup',
        ),
    ]
