# Generated by Django 3.2.7 on 2021-12-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_auto_20211228_1537'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ProductStock',
        ),
    ]
