# Generated by Django 3.1.13 on 2021-07-08 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegistrationOffer',
        ),
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
