# Generated by Django 3.1.13 on 2021-07-08 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0003_registrationoffer_voucher'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voucher',
        ),
    ]
