# Generated by Django 3.1.13 on 2021-07-10 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0005_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='title',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
