# Generated by Django 3.1.13 on 2021-07-11 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0006_voucher_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegistrationOffer',
            new_name='VoucherOffer',
        ),
    ]
