# Generated by Django 3.1.13 on 2021-07-11 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0008_voucheroffer_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='voucher',
            name='limit',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
