# Generated by Django 3.1.13 on 2021-07-12 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0013_auto_20210712_0557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='count',
        ),
        migrations.RemoveField(
            model_name='coupon',
            name='limit',
        ),
    ]
