# Generated by Django 3.1.13 on 2021-07-12 00:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0015_auto_20210712_0629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheroffer',
            name='discount',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(500)]),
        ),
    ]
