# Generated by Django 3.2.7 on 2021-10-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0018_alter_coupon_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucheroffer',
            name='user_valid_from',
            field=models.DateTimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='voucheroffer',
            name='user_valid_to',
            field=models.DateTimeField(blank=True),
        ),
    ]
