# Generated by Django 3.2.7 on 2021-10-07 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0021_alter_voucheroffer_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='condition_rate',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='limit',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='title',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_from',
        ),
        migrations.RemoveField(
            model_name='voucher',
            name='valid_to',
        ),
        migrations.AddField(
            model_name='voucher',
            name='voucher_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='coupons.voucheroffer'),
        ),
    ]
