# Generated by Django 3.2.7 on 2021-10-08 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0022_auto_20211007_1222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucheroffer',
            name='user_valid_from',
        ),
        migrations.RemoveField(
            model_name='voucheroffer',
            name='user_valid_to',
        ),
        migrations.AddField(
            model_name='voucher',
            name='user_valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='voucher',
            name='user_valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
