# Generated by Django 3.2.7 on 2021-10-08 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0023_auto_20211008_0708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voucher',
            name='user_valid_from',
        ),
    ]
